# Generated by Django 4.2.13 on 2024-06-24 12:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('full', models.BooleanField(default=False)),
                ('quickmatch', models.BooleanField(default=False)),
                ('invite_name', models.CharField(blank='true', max_length=255)),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None)),
            ],
        ),
    ]
