# Generated by Django 4.2.13 on 2024-06-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='invite_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
