# Generated by Django 4.2.13 on 2024-06-09 09:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='invite_name',
            field=models.CharField(blank='true', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=None),
        ),
    ]
