# Generated by Django 4.2.13 on 2024-06-23 06:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_room_invite_name_room_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None),
        ),
    ]
