# Generated by Django 4.2.13 on 2024-05-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_name_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
