# Generated by Django 4.2.13 on 2024-05-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
