# Generated by Django 4.2.13 on 2024-05-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='room_name',
        ),
    ]
