# Generated by Django 4.2.13 on 2024-05-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='friendrequest',
            table='users_friend_requests',
        ),
    ]
