# Generated by Django 4.2.13 on 2024-05-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_customuser_status_alter_customuser_friends_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
