# Generated by Django 4.2.13 on 2024-05-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=80)),
                ('password', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
