# Generated by Django 4.2.13 on 2024-05-29 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_chatmessage_room_name_chatmessage_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(default='default', max_length=255, unique=True),
        ),
    ]
