# Generated by Django 4.2.13 on 2024-05-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_remove_chatmessage_room_name_chatmessage_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='room',
            new_name='room_name',
        ),
    ]
