# Generated by Django 4.2.13 on 2024-05-30 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stat_management', '0002_alter_gamehistory_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gamehistory',
            table='users_game_history',
        ),
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('total_games_played', models.IntegerField(default=0)),
                ('total_hours_played', models.FloatField(default=0.0)),
                ('goal_scored', models.IntegerField(default=0)),
                ('goal_conceded', models.IntegerField(default=0)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_stats',
            },
        ),
    ]
