# Generated by Django 4.2.13 on 2024-05-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_management', '0003_alter_gamehistory_table_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
