# Generated by Django 4.2.13 on 2024-06-22 15:01

from django.db import migrations, models
import pyotp


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=32),
        ),
    ]
