# Generated by Django 4.2.13 on 2024-06-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_customuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_2fa_verified',
            field=models.BooleanField(default=False),
        ),
    ]
