# Generated by Django 4.2.13 on 2024-06-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_friendrequest_table'),
        ('user_management', '0004_customuser_blocked_users'),
    ]

    operations = [
    ]
