# Generated by Django 4.2.11 on 2024-04-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='id', max_length=255),
        ),
    ]
