# Generated by Django 4.2.11 on 2024-04-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='left',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='right',
            field=models.BooleanField(default=False),
        ),
    ]
