# Generated by Django 4.2.11 on 2024-04-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_left_room_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='left',
            field=models.BooleanField(default=False),
        ),
    ]
