# Generated by Django 4.2.13 on 2024-05-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gamehistory',
            table='game_history',
        ),
    ]
